version: '3.4'

services:

  node-app:
    image: nodeappimage-dev:v1
    container_name: ${NODE_APP_CONTAINER_NAME}
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: ${NODE_APP_CONTAINER_NAME_PORT}
      DB: ${MONGODB_URL}
      SALT: ${SALT}
    ports:
      - 10000:${NODE_APP_CONTAINER_NAME_PORT}
      - 9229:9229
    volumes:
      - ./backend:/work:rw
      - /work/node_modules
    networks:
      - docker_app_network
    command: ["yarn", "lintAndTest"]

volumes:
  mongodb_data:

networks:
  docker_app_network: