export const GET_HOSPITAL_ADMIN = 'GET_HOSPITAL_ADMIN';
export const ADD_HOSPITAL_ADMIN = 'ADD_HOSPITAL_ADMIN';
export const EDIT_HOSPITAL_ADMIN = 'ADD_HOSPITAL_ADMIN';
export const DELETE_HOSPITAL_ADMIN = 'DELETE_HOSPITAL_ADMIN';
